LITS/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from accounts.views import (login_view, register_view, logout_view, about_view, contacts_view)
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^comments/', include("comments.urls", namespace='comments')),
    url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^register/', register_view, name='register'),
    url(r'^about/', about_view, name='about'),
    url(r'^contacts/', contacts_view, name='contacts'),
    url(r'^', include('posts.urls', namespace='posts')),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf.urls import url
from posts.views import (
        post_create,
        post_detail,
        post_list,
        post_update,
        post_delete,
    )

urlpatterns = [
    url(r'^$', post_list, name='post_list'),
    url(r'^create/$', post_create, name='post_create'),
    url(r'^(?P<slug>[\w-]+)/$', post_detail, name='post_detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', post_update, name='post_update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete, name='post_delete'),
]

# urlpatterns = [
#     url(r'^$', post_list, name='post_list'),
#     url(r'^create/$', post_create, name='post_create'),
#     url(r'^(?P<id>\d+)/$', post_detail, name='post_detail'),
#     url(r'^(?P<id>\d+)/edit/$', post_update, name='post_update'),
#     url(r'^(?P<id>\d+)/delete/$', post_delete, name='post_delete'),
# ]

posts/models.py
from __future__ import unicode_literals
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.utils.safestring import mark_safe
from django.contrib.contenttypes.models import ContentType
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible

from markdown_deux import markdown
from comments.models import Comment

from .utils import get_read_time
# Create your models here.


class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        return super(PostManager,self).filter(draft=False).filter(publish__lte=timezone.now())

def upload_location(instance, filename):
    filename,
    return '%s/%s' %(instance.slug, filename)

@python_2_unicode_compatible
class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    title = models.CharField(max_length=120)
    slug = models.SlugField(max_length=50, unique=True, default=0)
    image = models.ImageField(upload_to=upload_location,
        null=True,
        blank=True,
        width_field='width_field',
        height_field='height_field')
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content = models.TextField()
    draft = models.BooleanField(default=False)
    publish = models.DateTimeField(auto_now=False, auto_now_add=False)
    read_time = models.IntegerField(default=0) #models.TimeField(null=True, blank=True)
    update = models.DateTimeField(auto_now = True, auto_now_add = False)
    timestamp = models.DateTimeField(auto_now = False, auto_now_add = True)

    objects = PostManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('posts:post_detail', kwargs={'slug':self.slug})
        # return '/posts/%s/' %(self.id)

    class Meta:
        ordering = ['-timestamp']

    def get_markdown(self):
        content = self.content
        markdown_text = markdown(content)
        return mark_safe(markdown_text)

    @property
    def comments(self):
        instance = self
        qs = Comment.objects.filter_by_instance(instance)
        return qs

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type

def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug=new_slug
    qs=Post.objects.filter(slug=slug).order_by('-id')
    exists = qs.exists()
    if exists:
        new_slug = '%s-%s' %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug

def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

    if instance.content:
        html_string = instance.get_markdown()
        read_time_var = get_read_time(html_string)
        instance.read_time = read_time_var

pre_save.connect(pre_save_post_receiver, sender=Post)

posts/forms.py
from django import forms

from pagedown.widgets import PagedownWidget

from .models import Post

class PostForm(forms.ModelForm):
    content = forms.CharField(widget=PagedownWidget(show_preview=False))
    publish = forms.DateField(widget=forms.SelectDateWidget)
    class Meta:
        model = Post
        fields = [
            'title',
            'content',
            'image',
            'draft',
            'publish',
        ]

posts/views.py
from urllib import quote_plus
from django.contrib import messages
from django.shortcuts import render, get_object_or_404,redirect
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils import timezone
from django.db.models import Q
from comments.forms import CommentForm
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.decorators import login_required


# Create your views here.
from comments.models import Comment
from .models import Post
from .forms import PostForm

def post_create(request):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    form=PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        messages.success(request,"Successfully Created")
        return HttpResponseRedirect(instance.get_absolute_url())

    context={
        'form': form
    }

    messages.error(request, 'Not Successfully Created')
    return render(request, 'post_form.html', context)

def post_detail(request, slug=None):
    # instance = Post.objects.get(pk=1)
    instance = get_object_or_404(Post,slug=slug)
    if instance.publish > timezone.now() or instance.draft:
        if not request.user.is_staff or not request.user.is_superuser:
            raise Http404
    share_string = quote_plus(instance.content)
    initial_data = {
        'content_type': instance.get_content_type,
        'object_id' : instance.id,
    }
    form = CommentForm(request.POST or None, initial = initial_data)
    if form.is_valid() and request.user.is_authenticated():
        c_type = form.cleaned_data.get('content_type')
        content_type = ContentType.objects.get(model=c_type)
        obj_id = form.cleaned_data.get('object_id')
        content_data = form.cleaned_data.get('content')
        parent_obj = None
        try:
            parent_id = int(request.POST.get('parent_id'))
        except:
            parent_id = None

        if parent_id:
            parent_qs = Comment.objects.filter(id = parent_id)
            if parent_qs.exists() and parent_qs.count() == 1:
                parent_obj = parent_qs.first()

        new_comment, created = Comment.objects.get_or_create(
                    user = request.user,
                    content_type = content_type,
                    object_id = obj_id,
                    content = content_data,
                    parent = parent_obj,
            )
        return HttpResponseRedirect(new_comment.content_object.get_absolute_url())

    comments = instance.comments
    context = {
        'title' : instance.title,
        'instance':instance,
        'share_string':share_string,
        'comments': comments,
        'comment_form': form,
    }
    return render(request, 'post_detail.html', context)

def post_list(request):
    today = timezone.now()
    queryset_list = Post.objects.active() #.order_by('-timestamp')
    if request.user.is_staff or request.user.is_superuser:
        queryset_list = Post.objects.all()

    query = request.GET.get('q')
    if query:
        queryset_list = queryset_list.filter(
            Q(title__icontains=query)|
            Q(content__icontains = query)|
            Q(user__first_name__icontains = query)|
            Q(user__last_name__icontains = query)
            ).distinct()
    paginator = Paginator(queryset_list, 4) # Show 25 contacts per page
    page_request_var = "page"
    page = request.GET.get(page_request_var)
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)
    context = {
        'object_list': queryset,
        'page_request_var': page_request_var,
        'today': today,
    }
    return render(request, 'post_list.html', context)

def post_update(request, slug=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post,slug=slug)
    form=PostForm(request.POST or None, request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request,"Successfully Updated")
        return HttpResponseRedirect(instance.get_absolute_url())

    context = {
        'title' : instance.title,
        'instance':instance,
        'form':form,
    }
    messages.error(request, 'Not Successfully Updated')
    return render(request, 'post_form.html', context)

@login_required
def post_delete(request, slug=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post,slug=slug)
    instance.delete()
    messages.success(request,"Post Successfully Deleted")
    return redirect("posts:post_list")

templates/about.html
{% extends 'base.html' %}

{% block content %}
<div class="row" >
<div class="container-fluid">
<div class="col-sm-8 col-sm-offset-2"">
<div class="thumbnail">
<br>
<h1 class="myfont" style="padding-left: 10px;">About us:</h1>
<br><br>

<p style="text-align: justify;">
Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lectus turpis, tempus non velit ut, sagittis sollicitudin ex. Nulla tincidunt lorem ut libero iaculis accumsan. Pellentesque accumsan viverra magna non congue. Donec lacinia varius faucibus. Ut in sollicitudin erat, vel dapibus lectus. Fusce sit amet tellus egestas, vestibulum sem vitae, gravida felis. Nullam pretium tellus ac velit dignissim lobortis. Nullam vestibulum eget est eget scelerisque.
Donec eget mauris dignissim, pharetra mi vitae, dapibus leo. Ut mi lacus, rhoncus sit amet pellentesque pretium, tristique ac nunc. Proin non feugiat elit. Morbi eu ultricies augue. Suspendisse tincidunt commodo sodales. Etiam a metus eu dolor consequat dictum eu aliquet nunc. Nulla tincidunt ante et augue sodales, id convallis quam efficitur.
Nulla eget nisl consequat, rhoncus risus nec, porttitor diam. Praesent vitae odio ante. Fusce velit purus, elementum in sapien id, placerat ultricies lacus. Curabitur id mauris varius sem faucibus consectetur rutrum consectetur lectus. Maecenas viverra a turpis a feugiat. Vivamus euismod justo massa, at semper sem congue facilisis. Proin condimentum orci et fringilla tempor. Curabitur sapien quam, lacinia in lorem a, eleifend auctor diam. Duis et pulvinar leo. Mauris cursus volutpat ipsum, ut aliquet leo molestie nec. Donec maximus lacinia mauris, a consectetur velit. Pellentesque mattis risus at lectus consequat imperdiet. Sed ut nibh in mauris tempus vehicula. Duis ac mollis erat. Nullam malesuada, orci sit amet auctor blandit, ante sapien pellentesque metus, ac tristique eros tellus eget felis.
In tincidunt dui et ultrices euismod. Fusce porttitor, ante nec egestas cursus, eros libero maximus nibh, placerat vehicula tellus diam eu mi. Ut ut dapibus ipsum, quis rutrum nulla. Vestibulum gravida ornare mauris id accumsan. Nulla ultrices elit dui, eu suscipit massa tristique vitae. Donec porta libero consectetur justo lacinia, eget commodo eros pretium. Proin vitae ullamcorper dolor. Cras finibus risus egestas scelerisque sodales.
Suspendisse non leo facilisis, sodales lacus sed, congue tellus. Quisque viverra faucibus eros, a efficitur sem blandit vel. Curabitur vehicula molestie magna non mollis. Curabitur lectus est, ullamcorper sit amet tellus finibus, euismod tempus velit. Aenean vitae orci et nulla ultrices venenatis sit amet at tortor. Sed mattis porta sodales. Donec metus justo, maximus in tincidunt vitae, viverra in libero. Suspendisse luctus a lorem ut accumsan. Ut sodales, ligula sed gravida tincidunt, nibh velit vehicula arcu, at tempus neque arcu vitae ante. </p>
</div>
</div>
</div>
</div>
{% endblock content %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>{% block head_title %}Title{% endblock head_title %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" type="text/css" href="{% static '/css/base.css' %}">
    {% block head_extra %}{% endblock head_extra %}
</head>
    <body>
                            <!-- NAVIGATION -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand mybrand" href="/">LITS Project</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
        <li><a href="/">Home <span class="sr-only">(current)</span></a></li>
        <li><a href="/about">About</a></li>
        <li><a href="/contacts">Contacts</a></li>
    </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" name="q" placeholder="Search posts" value="{{ request.GET.q }}" >
        </div>
        <button class="btn btn-default" type="submit">
        <i class="fa fa-search" aria-hidden="true"></i></button>
      </form>
    <ul class="nav navbar-nav navbar-right">
        {% if not request.user.is_authenticated %}
        <li class="pull-right"><a href="{% url 'register' %}">Register</a></li>
        <li class="pull-right"><a href="{% url 'login' %}">Login</a></li>
        {% else %}
        <li class="pull-right"><a href="{% url 'logout' %}">Logout ({{ request.user }})</a></li>
        {% endif %}
        {% if request.user.is_staff or request.user.is_superuser %}
        <li class="pull-right"><a href="{% url 'posts:post_create' %}">Create post</a></li>
        {% block post_detail_link %}{% endblock %}
        {% endif %}
    </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
{% include "messages_display.html" %}
{% block form_content %}{% endblock form_content %}
{% block content %}{% endblock content %}
<div id="fb-root">
<script>(function(d, s, id) {
var js, fjs = d.getElementsByTagName(s)[0];
if (d.getElementById(id)) return;
js = d.createElement(s); js.id = id;
js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.8";
fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
</div>
<script type="text/javascript">
  (function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/platform.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  })();
</script>
        <!-- jQuery -->
<script src = "https://code.jquery.com/jquery-1.12.4.min.js" integrity = "sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin = "anonymous"></script>
        <!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <!-- MarkDown CDN -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.6/marked.min.js"></script>
<script type="text/javascript">
$(document).ready(function(){
    $(".content-markdown").each(function(){
        var content = $(this).text()
        var markedContent = marked(content)
        $(this).html(markedContent)
    })
    $(".post-detail-item img").each(function(){
        $(this).addClass("img-responsive")
    })
    //preview-content
    var contentInput = $('#id_content');
    
    function setContent(value){
        var markedContent = marked(value)
        $('#preview-content').html(markedContent)
        $('#preview-content img').each(function(){
            $(this).addClass('img-responsive')
        })
    }
    setContent(contentInput.val())
    contentInput.keyup(function(){
        var newContent = $(this).val()
        setContent(newContent)
    })
        //preview-title
    var titleInput = $('#id_title');

    function setTitle(value){
        $('#preview-title').text(value)
    }
    setTitle(titleInput.val())

    titleInput.keyup(function(){
        var newContent = $(this).val()
        setTitle(newContent)
    })
    $('.comment-reply-btn').click(function(event){
        event.preventDefault();
        $(this).parent().next(".comment-reply").fadeToggle();
    })
 })
</script>
    </body>
</html>

templates/comment_thread.html
{% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}

{% block head_title %}
{{ instance.title }} | {{ block.super }}
{% endblock head_title %}


{% block content %}
{{ object }}

<div class='col-sm-6 col-sm-offset-3'>
          <p>{{ comment.content }}</p>
          <footer>via {{ comment.user }} | {{ comment.timestamp|timesince }} ago | {% if comment.children.count > 0 %}{{ comment.children.count }} Comment{% if comment.children.count > 1 %}s{% endif %} {% endif %}{% if request.user == comment.user %}<a href="{{ comment.get_delete_url }}">Delete</a>{% endif %}</footer>
          <hr/>
          <div>
              {% for child_comment in comment.children %}
                <blockquote>
                <p>{{ child_comment.content }}</p>
                <footer>via {{ child_comment.user }} | {{ child_comment.timestamp|timesince }} ago {% if request.user == child_comment.user %}<a href="{{ child_comment.get_delete_url }}">Delete</a>{% endif %}</footer>
                </blockquote>
             {% endfor %}
            {% if request.user.is_authenticated %}
            <form method="POST" action="."> {% csrf_token %}
                {{ form|crispy }}
                <input type='hidden' name='parent_id' value='{{ comment.id }}'>
                <input type='submit' value='Reply' class='btn btn-default'>
            </form>
            {% else %}
            <p>You must login to comment!</p>
            {% endif %}
        </div>
        <hr/>
</div>

{% endblock content %}

templates/confirm_delete.html
{% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}

{% block head_title %}
{{ instance.title }} | {{ block.super }}
{% endblock head_title %}

{% block content %}

<div class='col-sm-4 col-sm-offset-4 text-center'>
<h1>Confirm Delete</h1>
            <form method="POST" action="."> {% csrf_token %}
                <p>Are you sure you want to delete: "{{ object.content }}"?</p>
                <input type='submit' value='Confirm' class='btn btn-danger'>
                <a href="{{ object.get_absolute_url }}" class='btn btn-default'>Cancel</a>
            </form>
        </div>
        <hr/>
</div>

{% endblock content %}

templates/contacts.html
{% extends 'base.html' %}





{% block content %}
<div class="row">
    <div class="col-md-9 col-sm-offset-2"">
        <div class="thumbnail">
        <br>
        <h1 class="myfont" style="padding-left: 5px;">Contact us</h1>
        <hr>
        <br>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3 col-md-offset-2">
                <blockquote>
                    <p>
                    <i class="glyphicon glyphicon-earphone"></i><br>
                    <hr>
                    +38(050)839-21-11
                    <br>
                    +38(050)771-75-75
                    </p>
                </blockquote>
            </div>
            <div class="col-md-3">
                <blockquote>
                    <p><i class="glyphicon glyphicon-envelope"></i><br><hr>
                    lits-project@example.com
                    </p>
                </blockquote>
            </div>
            <div class="col-md-3">
                <blockquote>
                    <p><i class="glyphicon glyphicon-map-marker"></i><br><hr>
                    Headquarters:<br>1600 Amphitheatre Parkway<br>
                    Mountain View CA94043,<br>
                    United States</p>
                </blockquote>
            </div>
        </div>
        <hr>
    </div>
</div>
{% endblock content %}

templates/form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block form_content %}
<div class="col-sm-6 col-sm-offset-3 mystyle">
<h1>{{ title }}</h1>
<hr/>
<form method="POST" action="" enctype="multipart/form-data">{% csrf_token %}
    {{ form|crispy }}
    <input type="submit" class="btn btn-default" value="{{title}}">
</form>
</div>
{% endblock form_content %}

templates/messages_display.html
 {% if messages %}
    <div class='messages container'>
    {% for message in messages %}
    <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{% if "html_safe" in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}</div>
    {% endfor %}
    </div>
{% endif %}

templates/post_detail.html
{% extends 'base.html' %}
{% load urlify %}
{% load crispy_forms_tags %}

{% block head_title %}
{{ instance.title }} | {{ block.super }}
{% endblock head_title %}

{% block post_detail_link %}
<li class="pull-right"><a href="delete">Delete post</a></li>
<li class="pull-right"><a href="edit">Edit post</a></li>
{% endblock %}


{% block content %}
<div class="col-sm-8 col-sm-offset-2">
    {% if instance.image %}
    <img src="{{ instance.image.url }}" class="img-responsive" />
    {% endif %}
<h1 class="mytitle">{{ title }}</h1>
<p class="text-right">{{instance.publish}}<br><small>Read time: {% if instance.read_time <= 1 %} < 1 Minute {% else %}{{ instance.read_time }} minutes{% endif %}</small></p>
<h1><small>{% if instance.draft %} <span style="color: red; font-weight: bold;">Draft</span>{% endif %}</small></h1>
<hr>
<div class="row">
<div class="col-md-12">
    <div class="post-detail-item" style="text-align: justify;">{{instance.get_markdown}}</div>
{% if instance.user.get_full_name %}
    <p>Author: {{ instance.user.get_full_name }}</p>
{% endif %}
<hr/>
<div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-width="400" data-layout="button" data-action="like" data-size="large" data-show-faces="true" data-share="true"></div>
<hr>
<br/>
    <div>
    <p class="lead">Comments: </p>
    {% if request.user.is_authenticated %}
    <form method="POST" action="">{% csrf_token %}
    {{ comment_form|crispy}}
    <input type="submit" value="Post comment" class="btn btn-default">
    </form>
    {% else %}
    <p>You must login to comment!</p>
    {% endif %}
    <hr>
    {% for comment in comments %}
        <blockquote>
        <p>{{ comment.content }}</p>
        <footer>Author: {{ comment.user }} | {{ comment.timestamp|timesince }} ago | {% if comment.children.count > 0 %}{{ comment.children.count }} Comment{% if comment.children.count > 1 %}s{% endif %} |{% endif %}<a href="#" class="comment-reply-btn"> Reply</a> | <a href="{{ comment.get_absolute_url }}" class="">Thread</a></footer>
        <div class="comment-reply">
            {% for child_comment in comment.children %}
                <blockquote>
                <p>{{ child_comment.content }}</p>
                <footer>Author: {{ child_comment.user }}|{{ child_comment.timestamp|timesince }} ago</footer>
                </blockquote>
            {% endfor %}
            {% if request.user.is_authenticated %}
            <form method="POST" action="">{% csrf_token %}
                {{ comment_form|crispy}}
                <input type="hidden" name="parent_id" value="{{ comment.id }}">
                <input type="submit" value="Reply" class="btn btn-default">
            </form>
            {% else %}
            <p>You must login to comment!</p>
            {% endif %}
        </div>
        </blockquote>
        <hr>
    {% endfor %}
    </div>
</div>
</div>
</div>
{% endblock content %}

templates/post_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block head_extra %}
{{ form.media }}
{% endblock head_extra %}

{% block content %}
<div class="col-sm-6 mystyle">
<h1>Preview</h1>
<hr/>
<div class="content-preview">
    <h3 id="preview-title"></h3>
    <p id="preview-content"></p>
</div>
</div>
<div class="col-sm-6 mystyle">
<h1>Form</h1>
<hr/>
<form method="POST" action="" enctype="multipart/form-data">{% csrf_token %}
    {{ form|crispy }}
    <input type="submit" class="btn btn-default" value="Create post">
</form>
</div>
{% endblock %}